# Site Settings
lang: en
title: Home
tagline: SPAMLab
email: spamlab.iee@gmail.com
description: >
  Spatial Analysis And Modelling Lab website
baseurl: ""
url: "https://spamlab.github.io"
permalink: pretty
favicon: favicon.png
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#0e6655'
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

remote_theme: chrisrhymes/bulma-clean-theme

paginate: 5
paginate_path: "/blog/page:num"

excerpt_separator: <!--more-->

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: spamlab
  

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - jekyll-target-blank

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - pages/unused/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "SPAMLab"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
